language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install python-coveralls coverage pytest-cov pytest-timeout
  - echo TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} != "3" ]; then travis_retry pip install contextlib2; fi
  - python setup.py --version

# Run test
script:
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then py.test --cov=pystorm --cov-config .coveragerc --timeout=10; fi
  - if [ $TRAVIS_PYTHON_VERSION != "3.4" ]; then py.test --timeout=10; fi

# Calculate coverage on success
after_success:
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then coveralls --config_file .coveragerc; fi
