language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"

install:
  - travis_retry pip install --upgrade pip setuptools
  - travis_retry pip install --upgrade --upgrade-strategy only-if-needed -r test-requirements.txt
  - travis_retry pip install --upgrade --upgrade-strategy only-if-needed -r requirements.txt
  - echo TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - python setup.py --version

# Run test
script:
  - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then py.test --cov=pystorm --cov-config .coveragerc --timeout=10; fi
  - if [ $TRAVIS_PYTHON_VERSION != "3.6" ]; then py.test --timeout=10; fi

# Calculate coverage on success
after_success:
  - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then coveralls --config_file .coveragerc; fi
