package:
  name: pystorm
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}"

source:
  git_url: ./

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script:
    - cd $RECIPE_DIR
    - $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
    - six
    - simplejson

  run:
    - python
    - six
    - simplejson

test:
  imports:
    - pystorm
    - pystorm.bolt
    - pystorm.component
    - pystorm.spout

about:
  home: https://github.com/pystorm/pystorm
  license: Apache License 2.0
  summary: 'Battle-tested Apache Storm Multi-Lang implementation for Python.'
